spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/vemsDB
  username: postgres
  password: manager

  hikari:
   data-source-properties:
    stringtype: unspecified

 jpa:
  database: POSTGRESQL
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hibernate:
   ddl-auto: update   
  properties:
   hibernate:
    format_sql: true 

 sql:
  init:
   mode: always

eureka:
 instance:
  hostname: localhost

 client:
  service-url:
   defaultZone: http://localhost:9002/eureka

management:
 tracing:
  sampling:
   probability: 1.0
