spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vemsDB
    username: postgres
    password: manager
    hikari:
      data-source-properties:
        stringtype: unspecified

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.jdbc.time_zone: UTC

  batch:
    job:
      enabled: true

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:9002/eureka
