spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/vemsDB
  username: postgres
  password: manager
  
  jpa:
   hibernate:
    ddl-auto: create
    properties:
     hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
     show-sql: true

   sql:
    init:
     mode: always

eureka:
 instance:
  hostname: localhost

 client:
  service-url:
   defaultZone: http://localhost:9002/eureka

management:
 tracing:
  sampling:
   probability: 1.0
